### ISSUE TITLE
🐞 version appears twice in navbar 

### ISSUE THREAD

**Issue by prudhomm** [feelpp/antora-ui#29]
document version  selector appear twice in navbar, the first selector is not working

<img width="1432" alt="Screenshot 2023-05-10 at 09 55 38" src="https://github.com/feelpp/antora-ui/assets/151693/455070fa-83bb-48de-9e8c-48713f9ad760">

**Comment by ggrossetie** [comment]
As far as I remember that was already the case. This is the version "drawer" not the version selector:

<img width="277" alt="Capture d’écran 2023-05-10 à 11 09 42" src="https://github.com/feelpp/antora-ui/assets/333276/81232939-a833-40e6-a0a8-18b8556d156a">

Since there's no navigation it takes the whole vertical space.
Having said that, I agree that this is very confusing.

In my opinion, the "home" module should not be versioned and we should redesign the module/version drawer. Here's an example:


<img width="277" alt="Capture d’écran 2023-05-10 à 11 08 11" src="https://github.com/feelpp/antora-ui/assets/333276/92200148-2199-4f20-984b-235d0bd6c2e2">


And here's a mockup of the home page where the toolbar and the version drawer are removed:

![home](https://github.com/feelpp/antora-ui/assets/333276/1a8e1d51-cfa1-4990-bb65-adf578674222)
